name: auto-approve

on:
  pull_request:
    types: [ labeled ]

jobs:
  auto-approve:
    if: ${{ github.event.label.name == 'automated_pr' }}
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
