name: auto-merge

on:
  pull_request:
    types: [ labeled ]

jobs:
  auto-merge:
    if: ${{ github.event.label.name == 'automated_pr' }}
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for Automated PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
